/**
 * CMS Adapter — Converts HTML/CSS to CMS-specific templates.
 * Supports WordPress (PHP), Shopify (Liquid), and Strapi (JSON + React).
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CMSOutput {
  platform: "wordpress" | "shopify" | "strapi";
  files: Array<{ path: string; content: string; language: string }>;
  instructions: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function parseHtml(html: string): Document {
  const full = html.includes("<html") ? html : `<!DOCTYPE html><html><head></head><body>${html}</body></html>`;
  const parser = new DOMParser();
  return parser.parseFromString(full, "text/html");
}

function extractTitle(html: string): string {
  const doc = parseHtml(html);
  const h1 = doc.querySelector("h1");
  if (h1) return h1.textContent?.trim() ?? "My Site";
  return "My Site";
}

function slugify(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function pascalCase(str: string): string {
  return str.replace(/[^a-z0-9]/gi, " ").split(" ").filter(Boolean).map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join("");
}

// ─── WordPress Adapter ───────────────────────────────────────────────────────

export function adaptToWordPress(html: string, css: string, themeName: string): CMSOutput {
  const slug = slugify(themeName);
  const title = extractTitle(html);
  const files: Array<{ path: string; content: string; language: string }> = [];

  // Extract nav from HTML
  const doc = parseHtml(html);
  const nav = doc.querySelector("nav");
  const navHtml = nav ? nav.outerHTML : "";

  // Extract footer
  const footer = doc.querySelector("footer");
  const footerHtml = footer ? footer.outerHTML : "";

  // Remove nav and footer from main content for content area
  let contentHtml = html;
  if (nav) contentHtml = contentHtml.replace(nav.outerHTML, "");
  if (footer) contentHtml = contentHtml.replace(footer.outerHTML, "");

  // 1. style.css (theme metadata)
  files.push({
    path: `${slug}/style.css`,
    content: `/*
Theme Name: ${themeName}
Theme URI: https://example.com/${slug}
Author: LayoutForge
Author URI: https://example.com
Description: A custom WordPress theme generated by LayoutForge
Version: 1.0.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${slug}
*/

${css}`,
    language: "css",
  });

  // 2. functions.php
  files.push({
    path: `${slug}/functions.php`,
    content: `<?php
/**
 * ${themeName} Theme Functions
 * Generated by LayoutForge
 */

// Theme setup
function ${slug.replace(/-/g, "_")}_setup() {
  // Add title tag support
  add_theme_support('title-tag');

  // Add featured image support
  add_theme_support('post-thumbnails');

  // Add custom logo support
  add_theme_support('custom-logo', array(
    'height'      => 100,
    'width'       => 300,
    'flex-height' => true,
    'flex-width'  => true,
  ));

  // Register navigation menus
  register_nav_menus(array(
    'primary'   => __('Primary Menu', '${slug}'),
    'footer'    => __('Footer Menu', '${slug}'),
  ));

  // Add HTML5 support
  add_theme_support('html5', array(
    'search-form',
    'comment-form',
    'comment-list',
    'gallery',
    'caption',
  ));

  // Enqueue styles
  wp_enqueue_style('${slug}-style', get_stylesheet_uri(), array(), '1.0.0');
}
add_action('after_setup_theme', '${slug.replace(/-/g, "_")}_setup');

// Enqueue scripts and styles
function ${slug.replace(/-/g, "_")}_scripts() {
  wp_enqueue_style('${slug}-main', get_template_directory_uri() . '/assets/css/main.css', array(), '1.0.0');
}
add_action('wp_enqueue_scripts', '${slug.replace(/-/g, "_")}_scripts');
?>`,
    language: "php",
  });

  // 3. index.php
  files.push({
    path: `${slug}/index.php`,
    content: `<?php
/**
 * Main template file
 */
get_header();
?>

<main id="main-content" class="site-main">
  <?php if (have_posts()) : ?>
    <?php while (have_posts()) : the_post(); ?>
      <article id="post-<?php the_ID(); ?>" <?php post_class('mb-8'); ?>>
        <header class="entry-header mb-4">
          <h2 class="entry-title text-2xl font-bold">
            <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
          </h2>
          <div class="entry-meta text-sm text-slate-500">
            <time datetime="<?php echo get_the_date('c'); ?>"><?php echo get_the_date(); ?></time>
            <?php if (has_category()) : ?>
              <span class="mx-2">·</span>
              <?php the_category(', '); ?>
            <?php endif; ?>
          </div>
        </header>

        <div class="entry-summary text-slate-600 leading-relaxed">
          <?php the_excerpt(); ?>
        </div>

        <a href="<?php the_permalink(); ?>" class="inline-block mt-4 text-sm font-semibold text-indigo-600 hover:text-indigo-700">
          Read more →
        </a>
      </article>
    <?php endwhile; ?>

    <nav class="pagination mt-8">
      <?php
      the_posts_pagination(array(
        'mid_size'  => 2,
        'prev_text' => __('← Previous', '${slug}'),
        'next_text' => __('Next →', '${slug}'),
      ));
      ?>
    </nav>
  <?php else : ?>
    <p><?php esc_html_e('No posts found.', '${slug}'); ?></p>
  <?php endif; ?>
</main>

<?php get_footer(); ?>`,
    language: "php",
  });

  // 4. header.php
  files.push({
    path: `${slug}/header.php`,
    content: `<?php
/**
 * Header template
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

${navHtml ? navHtml.replace(/<nav/, '<nav aria-label="Main navigation"') : `<nav class="bg-white border-b border-slate-200" aria-label="Main navigation">
  <div class="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
    <a href="<?php echo esc_url(home_url('/')); ?>" class="text-xl font-extrabold text-slate-900">
      <?php bloginfo('name'); ?>
    </a>
    <?php
    wp_nav_menu(array(
      'theme_location' => 'primary',
      'container'      => false,
      'menu_class'     => 'flex items-center gap-6',
      'depth'          => 1,
    ));
    ?>
  </div>
</nav>`}
`,
    language: "php",
  });

  // 5. footer.php
  files.push({
    path: `${slug}/footer.php`,
    content: `<?php
/**
 * Footer template
 */
?>
${footerHtml || `<footer class="bg-slate-50 border-t border-slate-200 mt-20">
  <div class="max-w-6xl mx-auto px-6 py-8">
    <div class="flex items-center justify-between">
      <p class="text-sm text-slate-500">&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>. All rights reserved.</p>
      <?php
      wp_nav_menu(array(
        'theme_location' => 'footer',
        'container'      => false,
        'menu_class'     => 'flex items-center gap-4',
        'depth'          => 1,
      ));
      ?>
    </div>
  </div>
</footer>`}

<?php wp_footer(); ?>
</body>
</html>`,
    language: "php",
  });

  // 6. page.php
  files.push({
    path: `${slug}/page.php`,
    content: `<?php
/**
 * Page template
 */
get_header();
?>

<main id="main-content" class="max-w-6xl mx-auto px-6 py-16">
  <?php while (have_posts()) : the_post(); ?>
    <article id="page-<?php the_ID(); ?>" <?php post_class(); ?>>
      <header class="mb-8">
        <h1 class="text-4xl font-bold text-slate-900"><?php the_title(); ?></h1>
      </header>

      <div class="entry-content prose max-w-none">
        <?php the_content(); ?>
      </div>
    </article>
  <?php endwhile; ?>
</main>

<?php get_footer(); ?>`,
    language: "php",
  });

  // 7. single.php
  files.push({
    path: `${slug}/single.php`,
    content: `<?php
/**
 * Single post template
 */
get_header();
?>

<main id="main-content" class="max-w-3xl mx-auto px-6 py-16">
  <?php while (have_posts()) : the_post(); ?>
    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
      <header class="mb-8">
        <h1 class="text-4xl font-bold text-slate-900 mb-4"><?php the_title(); ?></h1>
        <div class="flex items-center gap-3 text-sm text-slate-500">
          <time datetime="<?php echo get_the_date('c'); ?>"><?php echo get_the_date(); ?></time>
          <?php if (has_category()) : ?>
            <span>·</span>
            <?php the_category(', '); ?>
          <?php endif; ?>
          <span>·</span>
          <span><?php echo esc_html(get_the_author()); ?></span>
        </div>
      </header>

      <?php if (has_post_thumbnail()) : ?>
        <div class="mb-8 rounded-2xl overflow-hidden">
          <?php the_post_thumbnail('large', array('class' => 'w-full h-auto')); ?>
        </div>
      <?php endif; ?>

      <div class="entry-content prose max-w-none">
        <?php the_content(); ?>
      </div>

      <footer class="mt-12 pt-8 border-t border-slate-200">
        <?php if (has_tag()) : ?>
          <div class="flex flex-wrap gap-2">
            <?php the_tags('<span class="px-2 py-0.5 bg-slate-100 text-slate-600 text-xs rounded">', '</span><span class="px-2 py-0.5 bg-slate-100 text-slate-600 text-xs rounded">', '</span>'); ?>
          </div>
        <?php endif; ?>
      </footer>
    </article>

    <?php
    the_post_navigation(array(
      'prev_text' => '<span class="text-sm text-slate-500">Previous</span><span class="font-semibold">%title</span>',
      'next_text' => '<span class="text-sm text-slate-500">Next</span><span class="font-semibold">%title</span>',
    ));
    ?>
  <?php endwhile; ?>
</main>

<?php get_footer(); ?>`,
    language: "php",
  });

  const instructions = `## WordPress Theme Setup

1. **Copy the theme folder** to \`wp-content/themes/${slug}/\`
2. **Activate the theme** in WordPress Admin → Appearance → Themes
3. **Set up menus** in Appearance → Menus (assign to Primary and Footer locations)
4. **Add your content** via the WordPress editor
5. **Customize** via Appearance → Customize

### Files included:
${files.map((f) => `- \`${f.path}\``).join("\n")}

### Requirements:
- WordPress 5.0+
- PHP 7.4+
- Tailwind CSS CDN is included via the theme`;

  return { platform: "wordpress", files, instructions };
}

// ─── Shopify Adapter ─────────────────────────────────────────────────────────

export function adaptToShopify(html: string, css: string, templateName: string): CMSOutput {
  const slug = slugify(templateName);
  const title = extractTitle(html);
  const files: Array<{ path: string; content: string; language: string }> = [];

  const doc = parseHtml(html);
  const nav = doc.querySelector("nav");
  const footer = doc.querySelector("footer");

  // 1. layout/theme.liquid
  files.push({
    path: `${slug}/layout/theme.liquid`,
    content: `<!DOCTYPE html>
<html lang="{{ request.locale.iso_code }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ page_title }} — {{ shop.name }}</title>
  <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
  <style>
    ${css}
  </style>
  {{ content_for_header }}
</head>
<body class="min-h-screen bg-white">
  {% section 'header' %}

  <main id="main-content" role="main">
    {{ content_for_layout }}
  </main>

  {% section 'footer' %}
</body>
</html>`,
    language: "liquid",
  });

  // 2. sections/header.liquid
  files.push({
    path: `${slug}/sections/header.liquid`,
    content: `<nav class="bg-white border-b border-slate-200" aria-label="Main navigation">
  <div class="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
    <a href="/" class="text-xl font-extrabold text-slate-900">
      {% if section.settings.logo != blank %}
        <img src="{{ section.settings.logo | image_url: width: 200 }}" alt="{{ shop.name }}" width="200" height="50">
      {% else %}
        {{ shop.name }}
      {% endif %}
    </a>

    <div class="flex items-center gap-6">
      {% for link in linklists[section.settings.menu].links %}
        <a href="{{ link.url }}" class="text-sm font-semibold {% if link.active %}text-indigo-600{% else %}text-slate-600 hover:text-slate-900{% endif %} transition-colors">
          {{ link.title }}
        </a>
      {% endfor %}

      <a href="/cart" class="relative">
        <svg class="w-5 h-5 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 100 4 2 2 0 000-4z"/></svg>
        {% if cart.item_count > 0 %}
          <span class="absolute -top-2 -right-2 w-5 h-5 bg-indigo-600 text-white text-[10px] font-bold rounded-full flex items-center justify-center">
            {{ cart.item_count }}
          </span>
        {% endif %}
      </a>
    </div>
  </div>
</nav>

{% schema %}
{
  "name": "Header",
  "settings": [
    {
      "type": "image_picker",
      "id": "logo",
      "label": "Logo"
    },
    {
      "type": "link_list",
      "id": "menu",
      "label": "Menu",
      "default": "main-menu"
    }
  ]
}
{% endschema %}`,
    language: "liquid",
  });

  // 3. sections/footer.liquid
  files.push({
    path: `${slug}/sections/footer.liquid`,
    content: `<footer class="bg-slate-50 border-t border-slate-200 mt-20">
  <div class="max-w-6xl mx-auto px-6 py-12">
    <div class="grid md:grid-cols-4 gap-8 mb-8">
      <div>
        <h3 class="text-lg font-extrabold text-slate-900 mb-4">{{ shop.name }}</h3>
        <p class="text-sm text-slate-600">{{ section.settings.description }}</p>
      </div>

      {% for block in section.blocks %}
        {% if block.type == 'link_list' %}
          <div>
            <h4 class="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">{{ block.settings.title }}</h4>
            <ul class="space-y-2">
              {% for link in linklists[block.settings.menu].links %}
                <li>
                  <a href="{{ link.url }}" class="text-sm text-slate-600 hover:text-slate-900 transition-colors">
                    {{ link.title }}
                  </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
      {% endfor %}
    </div>

    <div class="flex items-center justify-between pt-8 border-t border-slate-200">
      <p class="text-sm text-slate-500">&copy; {{ 'now' | date: "%Y" }} {{ shop.name }}. All rights reserved.</p>
      <div class="flex items-center gap-4">
        {% if section.settings.show_social %}
          {% if settings.social_instagram_link != blank %}
            <a href="{{ settings.social_instagram_link }}" class="text-slate-400 hover:text-slate-600" aria-label="Instagram">
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>
            </a>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</footer>

{% schema %}
{
  "name": "Footer",
  "settings": [
    {
      "type": "textarea",
      "id": "description",
      "label": "Description",
      "default": "Your store description goes here."
    },
    {
      "type": "checkbox",
      "id": "show_social",
      "label": "Show social icons",
      "default": true
    }
  ],
  "blocks": [
    {
      "type": "link_list",
      "name": "Menu",
      "settings": [
        {
          "type": "text",
          "id": "title",
          "label": "Title",
          "default": "Quick Links"
        },
        {
          "type": "link_list",
          "id": "menu",
          "label": "Menu"
        }
      ]
    }
  ],
  "max_blocks": 4,
  "presets": [
    {
      "name": "Footer"
    }
  ]
}
{% endschema %}`,
    language: "liquid",
  });

  // 4. templates/index.liquid
  files.push({
    path: `${slug}/templates/index.liquid`,
    content: `{% comment %}Homepage template{% endcomment %}

<div class="max-w-6xl mx-auto px-6 py-16">
  {% section 'hero' %}

  <div class="grid md:grid-cols-3 gap-8 mt-16">
    {% for product in collections.frontpage.products limit: 3 %}
      <div class="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
        <a href="{{ product.url }}">
          {% if product.featured_image %}
            <img src="{{ product.featured_image | image_url: width: 600 }}" alt="{{ product.featured_image.alt | escape }}" width="600" height="400" loading="lazy" class="w-full h-48 object-cover">
          {% endif %}
          <div class="p-6">
            <h3 class="text-lg font-bold text-slate-900 mb-2">{{ product.title }}</h3>
            <p class="text-sm text-slate-600 mb-4">{{ product.description | strip_html | truncate: 100 }}</p>
            <p class="text-lg font-extrabold text-slate-900">{{ product.price | money }}</p>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>`,
    language: "liquid",
  });

  // 5. sections/hero.liquid
  files.push({
    path: `${slug}/sections/hero.liquid`,
    content: `<section class="text-center py-16">
  <h1 class="text-4xl md:text-6xl font-extrabold text-slate-900 mb-4">
    {{ section.settings.heading | default: "${title}" }}
  </h1>
  <p class="text-lg text-slate-600 max-w-2xl mx-auto mb-8">
    {{ section.settings.subheading | default: "Welcome to our store" }}
  </p>
  {% if section.settings.button_text != blank %}
    <a href="{{ section.settings.button_link }}" class="inline-block bg-slate-900 text-white font-bold px-8 py-3.5 rounded-xl hover:bg-slate-800 transition-colors">
      {{ section.settings.button_text }}
    </a>
  {% endif %}
</section>

{% schema %}
{
  "name": "Hero",
  "settings": [
    {
      "type": "text",
      "id": "heading",
      "label": "Heading",
      "default": "Welcome to Our Store"
    },
    {
      "type": "textarea",
      "id": "subheading",
      "label": "Subheading",
      "default": "Discover our curated collection of products."
    },
    {
      "type": "text",
      "id": "button_text",
      "label": "Button text",
      "default": "Shop Now"
    },
    {
      "type": "url",
      "id": "button_link",
      "label": "Button link",
      "default": "/collections/all"
    }
  ],
  "presets": [
    {
      "name": "Hero Section"
    }
  ]
}
{% endschema %}`,
    language: "liquid",
  });

  // 6. templates/product.liquid
  files.push({
    path: `${slug}/templates/product.liquid`,
    content: `<div class="max-w-6xl mx-auto px-6 py-16">
  <div class="grid md:grid-cols-2 gap-12">
    <div>
      {% if product.featured_image %}
        <img src="{{ product.featured_image | image_url: width: 800 }}" alt="{{ product.featured_image.alt | escape }}" width="800" height="800" class="w-full rounded-2xl">
      {% endif %}
    </div>

    <div>
      <h1 class="text-3xl font-bold text-slate-900 mb-4">{{ product.title }}</h1>
      <p class="text-2xl font-extrabold text-slate-900 mb-6">{{ product.price | money }}</p>

      <div class="prose text-slate-600 mb-8">
        {{ product.description }}
      </div>

      {% form 'product', product %}
        <input type="hidden" name="id" value="{{ product.selected_or_first_available_variant.id }}">
        <button type="submit" class="w-full bg-slate-900 text-white font-bold py-3.5 px-6 rounded-xl hover:bg-slate-800 transition-colors">
          Add to Cart
        </button>
      {% endform %}
    </div>
  </div>
</div>`,
    language: "liquid",
  });

  const instructions = `## Shopify Theme Setup

1. **Upload the theme** via Shopify Admin → Online Store → Themes → Upload theme
2. **Preview and customize** via the theme editor
3. **Configure menus** in Online Store → Navigation
4. **Add products** via Products → Add product

### Files included:
${files.map((f) => `- \`${f.path}\``).join("\n")}

### Requirements:
- Shopify store (Basic plan or higher)
- Products and collections for dynamic content`;

  return { platform: "shopify", files, instructions };
}

// ─── Strapi Adapter ──────────────────────────────────────────────────────────

export function adaptToStrapi(html: string, css: string, componentName: string): CMSOutput {
  const name = pascalCase(componentName);
  const slug = slugify(componentName);
  const files: Array<{ path: string; content: string; language: string }> = [];

  const doc = parseHtml(html);
  const headings = Array.from(doc.querySelectorAll("h1,h2,h3"));
  const paragraphs = Array.from(doc.querySelectorAll("p"));
  const images = Array.from(doc.querySelectorAll("img"));

  // 1. Strapi component schema
  const fields: Array<{ name: string; type: string; required: boolean }> = [
    { name: "title", type: "string", required: true },
    { name: "subtitle", type: "text", required: false },
    { name: "content", type: "richtext", required: false },
  ];

  if (images.length > 0) {
    fields.push({ name: "heroImage", type: "media", required: false });
  }

  files.push({
    path: `strapi/components/${slug}.json`,
    content: JSON.stringify({
      collectionName: `components_${slug}`,
      info: {
        displayName: name,
        icon: "layer-group",
        description: `${name} component generated by LayoutForge`,
      },
      attributes: Object.fromEntries(
        fields.map((f) => [f.name, f.type === "media" ? { type: "media", multiple: false, allowedTypes: ["images"] } : { type: f.type, required: f.required }]),
      ),
    }, null, 2),
    language: "json",
  });

  // 2. Strapi page content type schema
  files.push({
    path: `strapi/src/api/${slug}/content-types/${slug}/schema.json`,
    content: JSON.stringify({
      kind: "collectionType",
      collectionName: slug,
      info: {
        singularName: slug,
        pluralName: `${slug}s`,
        displayName: name,
        description: `${name} pages managed by Strapi`,
      },
      options: { draftAndPublish: true },
      attributes: {
        title: { type: "string", required: true },
        slug: { type: "uid", targetField: "title" },
        description: { type: "text" },
        heroImage: { type: "media", multiple: false, allowedTypes: ["images"] },
        blocks: {
          type: "dynamiczone",
          components: [`${slug}.${slug}`],
        },
        seo: { type: "component", component: "shared.seo" },
      },
    }, null, 2),
    language: "json",
  });

  // 3. API route
  files.push({
    path: `strapi/src/api/${slug}/routes/${slug}.ts`,
    content: `/**
 * ${name} router
 */

import { factories } from '@strapi/strapi';

export default factories.createCoreRouter('api::${slug}.${slug}');
`,
    language: "typescript",
  });

  // 4. API controller
  files.push({
    path: `strapi/src/api/${slug}/controllers/${slug}.ts`,
    content: `/**
 * ${name} controller
 */

import { factories } from '@strapi/strapi';

export default factories.createCoreController('api::${slug}.${slug}');
`,
    language: "typescript",
  });

  // 5. API service
  files.push({
    path: `strapi/src/api/${slug}/services/${slug}.ts`,
    content: `/**
 * ${name} service
 */

import { factories } from '@strapi/strapi';

export default factories.createCoreService('api::${slug}.${slug}');
`,
    language: "typescript",
  });

  // 6. React frontend component
  const importLines = [`import React from 'react';`];
  const fetchLine = `const API_URL = process.env.NEXT_PUBLIC_STRAPI_URL || 'http://localhost:1337';`;

  files.push({
    path: `frontend/components/${name}.tsx`,
    content: `${importLines.join("\n")}

/**
 * ${name} — Strapi-powered React component
 * Generated by LayoutForge
 *
 * Fetches content from Strapi CMS and renders it.
 */

${fetchLine}

interface ${name}Data {
  id: number;
  attributes: {
    title: string;
    slug: string;
    description?: string;
    heroImage?: {
      data?: {
        attributes: {
          url: string;
          alternativeText?: string;
          width: number;
          height: number;
        };
      };
    };
    blocks?: Array<{
      __component: string;
      title?: string;
      subtitle?: string;
      content?: string;
    }>;
  };
}

interface ${name}Props {
  className?: string;
  /** If provided, skips fetching from Strapi */
  data?: ${name}Data;
}

async function fetchContent(): Promise<${name}Data[]> {
  const res = await fetch(\`\${API_URL}/api/${slug}s?populate=*\`, {
    next: { revalidate: 60 },
  });
  if (!res.ok) throw new Error('Failed to fetch content');
  const json = await res.json();
  return json.data;
}

export async function ${name}({ className = '', data }: ${name}Props) {
  const content = data ? [data] : await fetchContent();

  if (!content.length) {
    return (
      <div className="text-center py-20 text-slate-500">
        <p>No content available. Add content in Strapi.</p>
      </div>
    );
  }

  const page = content[0];
  const { title, description, heroImage, blocks } = page.attributes;

  return (
    <div className={\`min-h-screen \${className}\`}>
      {/* Hero */}
      <section className="max-w-6xl mx-auto px-6 py-16 text-center">
        <h1 className="text-4xl md:text-6xl font-extrabold text-slate-900 mb-4">
          {title}
        </h1>
        {description && (
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            {description}
          </p>
        )}
        {heroImage?.data && (
          <img
            src={\`\${API_URL}\${heroImage.data.attributes.url}\`}
            alt={heroImage.data.attributes.alternativeText || title}
            width={heroImage.data.attributes.width}
            height={heroImage.data.attributes.height}
            className="mt-8 rounded-2xl mx-auto"
          />
        )}
      </section>

      {/* Dynamic blocks */}
      {blocks?.map((block, idx) => (
        <section key={idx} className="max-w-6xl mx-auto px-6 py-12">
          {block.title && (
            <h2 className="text-2xl font-bold text-slate-900 mb-4">{block.title}</h2>
          )}
          {block.subtitle && (
            <p className="text-sm font-bold uppercase tracking-widest text-indigo-600 mb-3">{block.subtitle}</p>
          )}
          {block.content && (
            <div className="prose max-w-none text-slate-600" dangerouslySetInnerHTML={{ __html: block.content }} />
          )}
        </section>
      ))}
    </div>
  );
}

export default ${name};
`,
    language: "tsx",
  });

  // 7. Next.js page using the component
  files.push({
    path: `frontend/app/${slug}/page.tsx`,
    content: `import { ${name} } from '@/components/${name}';

/**
 * Next.js page for ${name}
 * Uses Strapi as headless CMS
 */

export const metadata = {
  title: '${name} — Powered by Strapi',
};

export default async function ${name}Page() {
  return <${name} />;
}
`,
    language: "tsx",
  });

  const instructions = `## Strapi + Next.js Setup

### Backend (Strapi):
1. \`npx create-strapi-app@latest ${slug}-cms --quickstart\`
2. Copy the component and API files to your Strapi project
3. Restart Strapi: \`npm run develop\`
4. Add content types via Content Manager
5. Set up API permissions in Settings → Roles → Public

### Frontend (Next.js):
1. Copy the React component to your Next.js project
2. Add environment variable: \`NEXT_PUBLIC_STRAPI_URL=http://localhost:1337\`
3. Install dependencies: \`npm install\`
4. Run: \`npm run dev\`

### Files included:
${files.map((f) => `- \`${f.path}\``).join("\n")}

### Requirements:
- Strapi v4+
- Node.js 18+
- Next.js 13+ (App Router)`;

  return { platform: "strapi", files, instructions };
}
