/**
 * HTML Sanitization utilities using DOMPurify.
 *
 * Provides safe defaults for sanitizing AI-generated HTML before
 * rendering in iframes or offering for download.
 */

import DOMPurify from "dompurify";

/**
 * Sanitize an HTML fragment for safe rendering in an iframe.
 *
 * - Strips all <script> tags
 * - Strips event handler attributes (onclick, onerror, etc.)
 * - Strips javascript: URLs in href/src
 * - Preserves inline styles, SVGs, images, structural HTML
 * - Allows data: URIs (needed for AI-generated inline images)
 * - Allows target="_blank" on links
 */
export function sanitizeHtmlForPreview(html: string): string {
  return DOMPurify.sanitize(html, {
    USE_PROFILES: { html: true, svg: true, svgFilters: true },
    ALLOW_DATA_ATTR: true,
    ADD_ATTR: ["target"],
    // Allow data: URIs for inline images generated by AI
    ALLOWED_URI_REGEXP:
      /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp|data):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
  });
}

/**
 * Sanitize HTML and also strip Tailwind CDN scripts/styles.
 *
 * This is a two-step process:
 * 1. DOMPurify removes XSS vectors (scripts, event handlers, etc.)
 * 2. Regex cleanup removes Tailwind browser scripts and related style blocks
 *    that would conflict with the iframe's own Tailwind processing.
 */
export function sanitizeForIframe(html: string): string {
  const clean = sanitizeHtmlForPreview(html);
  return (
    clean
      // Strip any remaining <script> tags (DOMPurify already does this, but belt-and-suspenders)
      .replace(/<script[\s\S]*?<\/script>/gi, "")
      .replace(/<script[\s\S]*?\/?>/gi, "")
      // Strip Tailwind-related <style> blocks
      .replace(
        /<style[^>]*>[\s\S]*?@(?:import\s+["']tailwindcss|tailwind\s)[\s\S]*?<\/style>/gi,
        "",
      )
      // Strip Tailwind CDN <link> tags
      .replace(/<link[^>]*(?:tailwindcss|tailwind)[^>]*\/?>/gi, "")
  );
}

/**
 * Sanitize HTML for download (same as iframe but with additional cleanup).
 */
export function sanitizeForDownload(html: string): string {
  return sanitizeForIframe(html);
}
