/**
 * Storybook Exporter — Generates Storybook stories, configuration,
 * and preview files from HTML/CSS components.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface StorybookOutput {
  stories: Array<{ name: string; content: string; filename: string }>;
  config: string;   // .storybook/main.ts
  preview: string;  // .storybook/preview.ts
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function pascalCase(str: string): string {
  return str
    .replace(/[^a-z0-9]/gi, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function analyzeHtml(html: string): {
  colors: string[];
  textContent: string[];
  hasImages: boolean;
  hasButtons: boolean;
  hasLinks: boolean;
  hasForm: boolean;
  headings: string[];
} {
  const parser = new DOMParser();
  const full = html.includes("<html") ? html : `<html><body>${html}</body></html>`;
  const doc = parser.parseFromString(full, "text/html");

  // Extract colors from classes
  const colorRegex = /(?:text|bg|border)-(\w+-\d+)/g;
  const colors = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = colorRegex.exec(html)) !== null) {
    colors.add(m[1]);
  }

  const textContent: string[] = [];
  doc.querySelectorAll("p, h1, h2, h3, h4, h5, h6").forEach((el) => {
    const t = el.textContent?.trim();
    if (t && t.length < 80) textContent.push(t);
  });

  const headings: string[] = [];
  doc.querySelectorAll("h1,h2,h3,h4,h5,h6").forEach((h) => {
    const t = h.textContent?.trim();
    if (t) headings.push(t);
  });

  return {
    colors: [...colors].slice(0, 8),
    textContent: textContent.slice(0, 6),
    hasImages: doc.querySelectorAll("img").length > 0,
    hasButtons: doc.querySelectorAll("button").length > 0,
    hasLinks: doc.querySelectorAll("a").length > 0,
    hasForm: doc.querySelectorAll("form").length > 0,
    headings,
  };
}

// ─── Story Generator ─────────────────────────────────────────────────────────

export function generateStorybookStories(
  html: string,
  css: string,
  componentName: string,
): StorybookOutput {
  const name = pascalCase(componentName);
  const analysis = analyzeHtml(html);
  const stories: Array<{ name: string; content: string; filename: string }> = [];

  // 1. Default story (full component)
  const defaultStory = `import type { Meta, StoryObj } from '@storybook/react';
import { ${name} } from './${name}';

/**
 * ${name} — Full component story
 * Generated by LayoutForge
 */
const meta: Meta<typeof ${name}> = {
  title: 'Components/${name}',
  component: ${name},
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
  },
  argTypes: {
    ${analysis.colors.length > 0 ? `// Color controls
    ${analysis.colors.slice(0, 4).map((c) => {
      const [prefix, shade] = c.split("-");
      return `${prefix}Color: {
        control: { type: 'select' },
        options: ['${prefix}-50', '${prefix}-100', '${prefix}-200', '${prefix}-300', '${prefix}-400', '${prefix}-500', '${prefix}-600', '${prefix}-700', '${prefix}-800', '${prefix}-900'],
        defaultValue: '${c}',
      }`;
    }).join(",\n    ")}${analysis.hasButtons ? "," : ""}` : ""}
    ${analysis.hasButtons ? `buttonText: {
      control: { type: 'text' },
      defaultValue: 'Click me',
    }` : ""}
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Default story with all default props
 */
export const Default: Story = {
  args: {},
};

${analysis.textContent.length > 0 ? `/**
 * Custom content variant
 */
export const CustomContent: Story = {
  args: {
    // Override content props here
  },
  parameters: {
    docs: {
      description: {
        story: 'Component with custom content overrides.',
      },
    },
  },
};
` : ""}
${analysis.hasButtons ? `/**
 * Interactive variant with buttons
 */
export const WithInteraction: Story = {
  args: {},
  play: async ({ canvasElement }) => {
    // Add interaction tests here
    // const canvas = within(canvasElement);
    // const button = canvas.getByRole('button', { name: /click me/i });
    // await userEvent.click(button);
  },
};
` : ""}
${analysis.hasImages ? `/**
 * With images variant
 */
export const WithImages: Story = {
  args: {},
  parameters: {
    docs: {
      description: {
        story: 'Component displaying images. Ensure all images have alt text.',
      },
    },
  },
};
` : ""}
${analysis.hasForm ? `/**
 * Form variant
 */
export const WithForm: Story = {
  args: {},
  play: async ({ canvasElement }) => {
    // Add form interaction tests here
    // const canvas = within(canvasElement);
  },
};
` : ""}
/**
 * Dark background variant
 */
export const DarkBackground: Story = {
  args: {},
  parameters: {
    backgrounds: { default: 'dark' },
  },
};

/**
 * Mobile viewport variant
 */
export const Mobile: Story = {
  args: {},
  parameters: {
    viewport: {
      defaultViewport: 'mobile1',
    },
  },
};
`;
  stories.push({
    name: "Default",
    content: defaultStory,
    filename: `${name}.stories.tsx`,
  });

  // 2. Variants story
  const variantsStory = `import type { Meta, StoryObj } from '@storybook/react';
import { ${name} } from './${name}';

const meta: Meta<typeof ${name}> = {
  title: 'Variants/${name}',
  component: ${name},
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Compact layout variant
 */
export const Compact: Story = {
  args: {},
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        story: 'Compact layout with reduced spacing.',
      },
    },
  },
};

/**
 * Full-width variant
 */
export const FullWidth: Story = {
  args: {},
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        story: 'Full-width layout without container constraints.',
      },
    },
  },
};

/**
 * RTL (Right-to-Left) variant
 */
export const RTL: Story = {
  args: {},
  parameters: {
    direction: 'rtl',
    docs: {
      description: {
        story: 'Component rendered in right-to-left direction.',
      },
    },
  },
};

/**
 * High contrast variant
 */
export const HighContrast: Story = {
  args: {},
  parameters: {
    a11y: {
      config: {
        rules: [
          { id: 'color-contrast', options: { noScroll: true } },
        ],
      },
    },
  },
};
`;
  stories.push({
    name: "Variants",
    content: variantsStory,
    filename: `${name}Variants.stories.tsx`,
  });

  // 3. Configuration files
  const config = `import type { StorybookConfig } from '@storybook/react-vite';

/**
 * Storybook configuration
 * Generated by LayoutForge
 */
const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-a11y',
    '@storybook/addon-viewport',
    '@storybook/addon-backgrounds',
  ],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  typescript: {
    reactDocgen: 'react-docgen-typescript',
  },
};

export default config;
`;

  const preview = `import type { Preview } from '@storybook/react';
import '../src/index.css';

/**
 * Storybook preview configuration
 * Generated by LayoutForge
 */
const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    backgrounds: {
      default: 'light',
      values: [
        { name: 'light', value: '#ffffff' },
        { name: 'dark', value: '#0f172a' },
        { name: 'gray', value: '#f1f5f9' },
      ],
    },
    viewport: {
      viewports: {
        mobile: {
          name: 'Mobile',
          styles: { width: '375px', height: '812px' },
        },
        tablet: {
          name: 'Tablet',
          styles: { width: '768px', height: '1024px' },
        },
        desktop: {
          name: 'Desktop',
          styles: { width: '1280px', height: '800px' },
        },
      },
    },
    a11y: {
      config: {},
      options: {
        checks: { 'color-contrast': { options: { noScroll: true } } },
        restoreScroll: true,
      },
    },
  },
};

export default preview;
`;

  return { stories, config, preview };
}
